const express=require('express');const session=require('express-session');const bcrypt=require('bcryptjs');const multer=require('multer');const path=require('path');const fs=require('fs');
const app=express(),PORT=process.env.PORT||3000,ROOT=__dirname,DB_FILE=path.join(ROOT,'data.json'),UPLOADS=path.join(ROOT,'uploads');fs.mkdirSync(UPLOADS,{recursive:true});
function save(){fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))}function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let db;if(fs.existsSync(DB_FILE))db=JSON.parse(fs.readFileSync(DB_FILE));else{db={settings:{site_name:'Javier Proyect'},users:[],projects:[]};db.users.push({id:1,username:'Ale2007a',password:bcrypt.hashSync('Ale2007',12),role:'admin'});save()}
const appPage=(title,body,user)=>`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · ${esc(db.settings.site_name)}</title><link rel="stylesheet" href="/style.css"></head><body><header><a class="brand" href="/">${esc(db.settings.site_name)}</a><nav><a href="/">Inicio</a>${user?'<a href="/admin">Panel</a><a href="/logout">Salir</a>':'<a href="/login">Admin</a>'}</nav></header><main>${body}</main><footer>${esc(db.settings.site_name)} · Proyectos Arduino</footer></body></html>`;
app.use(express.urlencoded({extended:true,limit:'2mb'}));app.set('trust proxy', 1);app.use(session({secret:process.env.SESSION_SECRET||'clave-secreta-javier-2026',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:true}}));app.use('/uploads',express.static(UPLOADS));app.use(express.static(path.join(ROOT,'public')));
const storage=multer.diskStorage({destination:(_,__,cb)=>cb(null,UPLOADS),filename:(_,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))});const upload=multer({storage,limits:{fileSize:8*1024*1024}});function auth(req,res,next){if(req.session.user)return next();res.redirect('/login')}function isAdmin(req,res,next){if(req.session.user?.role==='admin')return next();res.status(403).send(appPage('403','<div class="card"><h1>Acceso denegado</h1></div>',req.session.user))}
app.get('/',(req,res)=>{const q=(req.query.q||'').toLowerCase();const ps=db.projects.filter(p=>!q||p.title.toLowerCase().includes(q)||p.description.toLowerCase().includes(q));const cards=ps.map(p=>`<article class="project">${p.image?`<img src="/uploads/${esc(p.image)}" alt="">`:'<div class="placeholder">ARDUINO</div>'}<div class="pad"><h2>${esc(p.title)}</h2><p>${esc(p.description).slice(0,180)}</p><a class="btn" href="/project/${p.id}">Ver proyecto →</a></div></article>`).join('');res.send(appPage('Inicio',`<section class="hero"><span class="tag">REPOSITORIO ARDUINO</span><h1>Aprende, crea y comparte proyectos.</h1><p>Diagramas, códigos, materiales y proyectos en un solo lugar.</p><form class="search"><input name="q" value="${esc(req.query.q||'')}" placeholder="Buscar proyectos..."><button>Buscar</button></form></section><section><div class="sectionhead"><h2>Proyectos publicados</h2><span>${ps.length} resultado(s)</span></div><div class="grid">${cards||'<div class="card"><h3>Aún no hay proyectos</h3><p>Publica el primero desde el panel.</p></div>'}</div></section>`,req.session.user))});
app.get('/project/:id',(req,res)=>{const p=db.projects.find(x=>x.id===Number(req.params.id));if(!p)return res.status(404).send(appPage('No encontrado','<div class="card"><h1>Proyecto no encontrado</h1></div>'));res.send(appPage(p.title,`<article class="detail"><a href="/">← Volver</a><h1>${esc(p.title)}</h1><p class="lead">${esc(p.description)}</p>${p.image?`<img class="detailimg" src="/uploads/${esc(p.image)}" alt="">`:''}${p.materials?`<section class="box"><h2>🧰 Materiales</h2><pre>${esc(p.materials)}</pre></section>`:''}${p.diagram?`<section class="box"><h2>🔌 Diagrama</h2><img class="diagram" src="/uploads/${esc(p.diagram)}"></section>`:''}${p.code?`<section class="box"><h2>💻 Código Arduino</h2><pre class="code">${esc(p.code)}</pre></section>`:''}${p.file?`<p><a class="btn" href="/uploads/${esc(p.file)}">Descargar archivo</a></p>`:''}</article>`,req.session.user))});
app.get('/login',(req,res)=>res.send(appPage('Administración',`<div class="auth card"><h1>Panel de administración</h1><form method="post" action="/login"><label>Usuario<input name="username" required></label><label>Contraseña<input type="password" name="password" required></label><button>Entrar</button></form></div>`)));app.post('/login',(req,res)=>{const u=db.users.find(x=>x.username===req.body.username);if(!u||!bcrypt.compareSync(req.body.password,u.password))return res.status(401).send(appPage('Error','<div class="card"><h1>Datos incorrectos</h1><a href="/login">Intentar de nuevo</a></div>'));req.session.user={id:u.id,username:u.username,role:u.role};res.redirect('/admin')});app.get('/logout',(req,res)=>req.session.destroy(()=>res.redirect('/')));
app.get('/admin',auth,(req,res)=>{const rows=db.projects.map(p=>`<tr><td>${esc(p.title)}</td><td><a href="/project/${p.id}">Ver</a></td><td><form method="post" action="/admin/delete/${p.id}" onsubmit="return confirm('¿Eliminar proyecto?')"><button class="danger">Eliminar</button></form></td></tr>`).join('');res.send(appPage('Panel',`<span class="tag">ADMINISTRACIÓN</span><h1>Panel de ${esc(req.session.user.username)}</h1><div class="adminnav"><a class="btn" href="/admin/new">+ Nuevo proyecto</a><a class="btn secondary" href="/admin/account">Mi cuenta</a>${req.session.user.role==='admin'?'<a class="btn secondary" href="/admin/users">Usuarios</a><a class="btn secondary" href="/admin/settings">Cambiar nombre</a>':''}</div><div class="card"><h2>Proyectos</h2><table><tr><th>Proyecto</th><th></th><th></th></tr>${rows||'<tr><td colspan="3">Sin proyectos</td></tr>'}</table></div>`,req.session.user))});
const form=()=>`<div class="card"><h1>Nuevo proyecto</h1><form method="post" enctype="multipart/form-data"><label>Nombre<input name="title" required></label><label>Descripción<textarea name="description"></textarea></label><label>Materiales<textarea name="materials"></textarea></label><label>Código Arduino<textarea name="code" class="codeinput"></textarea></label><label>Imagen<input type="file" name="image" accept="image/*"></label><label>Diagrama<input type="file" name="diagram" accept="image/*"></label><label>Archivo .ino<input type="file" name="file" accept=".ino,.txt"></label><button>Publicar proyecto</button></form></div>`;app.get('/admin/new',auth,(req,res)=>res.send(appPage('Nuevo',form(),req.session.user)));app.post('/admin/new',auth,upload.fields([{name:'image',maxCount:1},{name:'diagram',maxCount:1},{name:'file',maxCount:1}]),(req,res)=>{const f=req.files||{};db.projects.push({id:db.projects.length?Math.max(...db.projects.map(x=>x.id))+1:1,title:req.body.title,description:req.body.description||'',materials:req.body.materials||'',code:req.body.code||'',image:f.image?.[0]?.filename||'',diagram:f.diagram?.[0]?.filename||'',file:f.file?.[0]?.filename||''});save();res.redirect('/admin')});app.post('/admin/delete/:id',auth,(req,res)=>{db.projects=db.projects.filter(p=>p.id!==Number(req.params.id));save();res.redirect('/admin')});
app.get('/admin/account',auth,(req,res)=>{const u=db.users.find(x=>x.id===req.session.user.id);res.send(appPage('Mi cuenta',`<div class="card"><h1>Mi cuenta</h1><form method="post"><label>Nuevo usuario<input name="username" required value="${esc(u.username)}"></label><label>Contraseña actual<input type="password" name="current_password" required></label><label>Nueva contraseña<input type="password" name="new_password" minlength="8"></label><label>Repetir nueva contraseña<input type="password" name="confirm_password" minlength="8"></label><button>Guardar cambios</button></form></div>`,req.session.user))});app.post('/admin/account',auth,(req,res)=>{const u=db.users.find(x=>x.id===req.session.user.id),np=req.body.new_password||'',cp=req.body.confirm_password||'',un=(req.body.username||'').trim();if(!bcrypt.compareSync(req.body.current_password||'',u.password))return res.status(400).send(appPage('Error','<div class="card"><h1>Contraseña actual incorrecta</h1></div>',req.session.user));if(!un||db.users.some(x=>x.id!==u.id&&x.username===un))return res.status(400).send(appPage('Error','<div class="card"><h1>Usuario inválido o ya existente.</h1></div>',req.session.user));if(np&&np.length<8||np!==cp)return res.status(400).send(appPage('Error','<div class="card"><h1>Revisa la nueva contraseña.</h1></div>',req.session.user));u.username=un;if(np)u.password=bcrypt.hashSync(np,12);save();req.session.user.username=un;res.redirect('/admin')});
app.get('/admin/settings',isAdmin,(req,res)=>res.send(appPage('Ajustes',`<div class="card"><h1>Nombre de la página</h1><form method="post"><label>Nombre<input name="site_name" required value="${esc(db.settings.site_name)}"></label><button>Guardar nombre</button></form></div>`,req.session.user)));app.post('/admin/settings',isAdmin,(req,res)=>{db.settings.site_name=(req.body.site_name||'Javier Proyect').trim()||'Javier Proyect';save();res.redirect('/admin')});
app.get('/admin/users',isAdmin,(req,res)=>{const rows=db.users.map(u=>`<tr><td>${esc(u.username)}</td><td>${u.role}</td><td>${u.id===req.session.user.id?'Tú':`<form method="post" action="/admin/users/role/${u.id}" style="display:inline"><select name="role" onchange="this.form.submit()"><option value="editor" ${u.role==='editor'?'selected':''}>Editor</option><option value="admin" \( {u.role==='admin'?'selected':''}>Administrador</option></select></form> <form method="post" action="/admin/users/delete/ \){u.id}" style="display:inline" onsubmit="return confirm('¿Eliminar?')"><button class="danger">Eliminar</button></form>`}</td></tr>`).join('');res.send(appPage('Usuarios',`<div class="card"><h1>Administrar usuarios</h1><form method="post"><label>Usuario<input name="username" required></label><label>Contraseña<input type="password" name="password" minlength="8" required></label><label>Rol<select name="role"><option value="editor">Editor</option><option value="admin">Administrador</option></select></label><button>Crear usuario</button></form></div><div class="card"><h2>Usuarios</h2><table><tr><th>Usuario</th><th>Rol</th><th></th></tr>${rows}</table></div>`,req.session.user))});app.post('/admin/users',isAdmin,(req,res)=>{if(db.users.some(x=>x.username===req.body.username))return res.status(400).send(appPage('Error','<div class="card"><h1>Ese usuario ya existe.</h1></div>',req.session.user));db.users.push({id:db.users.length?Math.max(...db.users.map(x=>x.id))+1:1,username:req.body.username,password:bcrypt.hashSync(req.body.password,12),role:req.body.role==='admin'?'admin':'editor'});save();res.redirect('/admin/users')});app.post('/admin/users/role/:id', isAdmin, (req,res)=>{
    const user = db.users.find(u => u.id === Number(req.params.id));

    if (!user) {
        return res.status(404).send(
            appPage('Error', '<div class="card"><h1>Usuario no encontrado</h1></div>', req.session.user)
        );
    }

    if (user.id === req.session.user.id) {
        return res.status(400).send(
            appPage('Error', '<div class="card"><h1>No puedes cambiar tu propio rol</h1></div>', req.session.user)
        );
    }

    if (req.body.role !== 'admin' && req.body.role !== 'editor') {
        return res.status(400).send(
            appPage('Error', '<div class="card"><h1>Rol no válido</h1></div>', req.session.user)
        );
    }

    user.role = req.body.role;
    save();

    res.redirect('/admin/users');
});app.post('/admin/users/delete/:id',isAdmin,(req,res)=>{db.users=db.users.filter(u=>u.id!==Number(req.params.id)||u.id===req.session.user.id);save();res.redirect('/admin/users')});
app.listen(PORT,()=>console.log('Javier Proyect en http://localhost:'+PORT));
